mkdir .\sqr
mkdir .\sqr\log
mkdir .\sqr\output
mkdir .\sqr\include
mkdir .\sqr\include\labels
mkdir .\sqr\include\czech
mkdir .\sqr\include\doc
mkdir .\sqr\include\american
mkdir .\sqr\include\dutch
mkdir .\sqr\include\french
mkdir .\sqr\include\german
mkdir .\sqr\include\hungarian
mkdir .\sqr\include\italian
mkdir .\sqr\include\polish
mkdir .\sqr\include\portuguese
mkdir .\sqr\include\slovenian
mkdir .\sqr\include\spanish
mkdir .\sqr\include\norwegian
mkdir .\sqr\include\romanian
mkdir .\sqr\src
mkdir .\sqr\ovl
mkdir .\sqr\fonts
mkdir .\sqr\tmp
mkdir .\sqr\workspace
mkdir .\sqr\MH
mkdir .\sqr\MH\save
mkdir .\kunden
mkdir .\kunden\li_inc
mkdir .\kunden\li_inc\save
mkdir .\kunden\li_module
mkdir .\kunden\sh
mkdir .\kunden\sh\save
mkdir .\kunden\sh\pids
mkdir .\kunden\sqr
mkdir .\kunden\sqr\include
mkdir .\kunden\sqr\include\save
mkdir .\kunden\sqr\src
mkdir .\kunden\QAEDI
mkdir .\kunden\conf
mkdir .\kunden\conf\archiv
mkdir .\kunden\fglc
mkdir .\kunden\etc
mkdir .\binlnx
mkdir .\local
mkdir .\local\bin
mkdir .\local\etc
mkdir .\etc
mkdir .\etc\.lirun
mkdir .\fglc
mkdir .\li_inc
mkdir .\li_module
mkdir .\li_module\var
mkdir .\perl
mkdir .\samples
mkdir .\samples\html
mkdir .\samples\html\localized
mkdir .\samples\html\simple
mkdir .\sh
mkdir .\sh\install
mkdir .\sh\install\mandant
mkdir .\sh\sqr
mkdir .\sh\tools
mkdir .\sql
mkdir .\sql\tools
mkdir .\tab
mkdir .\binhpux
mkdir .\binaix
mkdir .\cbus
mkdir .\cbus\DBDEMO1
mkdir .\cbus\DBDEMO2
mkdir .\fonts
mkdir .\li_dev
mkdir .\configdef
mkdir .\logos
mkdir .\li_rt
mkdir .\license
mkdir .\license\PLJSON
mkdir .\conf
mkdir .\conf\archiv
mkdir .\java
mkdir .\util
mkdir .\util\pldoc
mkdir .\util\pldoc\samples
mkdir .\util\pldoc\target